2020-07-06 01:19:35,793 [INFO] ========== Models Load time ==========
2020-07-06 01:19:36,325 [INFO] Face Detection Model: 530.0ms
2020-07-06 01:19:36,454 [INFO] Headpose Estimation Model: 125.4ms
2020-07-06 01:19:36,531 [INFO] Facial Landmarks Detection Model: 76.6ms
2020-07-06 01:19:36,670 [INFO] Gaze Estimation Model: 137.0ms
2020-07-06 01:19:36,671 [INFO] ========== End ==========
2020-07-06 01:19:52,333 [INFO] ========== Models Inference time ==========
2020-07-06 01:19:52,336 [INFO] Face Detection Model:53.7ms
2020-07-06 01:19:52,338 [INFO] Facial Landmarks Detection Model:0.9ms
2020-07-06 01:19:52,340 [INFO] Headpose Estimation Model:3.0ms
2020-07-06 01:19:52,341 [INFO] Gaze Estimation Model:3.6ms
2020-07-06 01:19:52,341 [INFO] ========== End ==========
2020-07-06 01:28:07,140 [INFO] ========== Models Load time ==========
2020-07-06 01:28:07,380 [INFO] Face Detection Model: 237.4ms
2020-07-06 01:28:07,492 [INFO] Headpose Estimation Model: 108.7ms
2020-07-06 01:28:07,568 [INFO] Facial Landmarks Detection Model: 74.3ms
2020-07-06 01:28:07,699 [INFO] Gaze Estimation Model: 129.5ms
2020-07-06 01:28:07,701 [INFO] ========== End ==========
2020-07-06 01:28:22,631 [INFO] ========== Models Inference time ==========
2020-07-06 01:28:22,633 [INFO] Face Detection Model:52.2ms
2020-07-06 01:28:22,636 [INFO] Facial Landmarks Detection Model:0.9ms
2020-07-06 01:28:22,638 [INFO] Headpose Estimation Model:2.9ms
2020-07-06 01:28:22,639 [INFO] Gaze Estimation Model:3.6ms
2020-07-06 01:28:22,639 [INFO] ========== End ==========
2020-07-06 01:37:40,853 [INFO] ========== Models Load time ==========
2020-07-06 01:37:41,097 [INFO] Face Detection Model: 242.0ms
2020-07-06 01:37:41,873 [INFO] Headpose Estimation Model: 773.5ms
2020-07-06 01:37:42,040 [INFO] Facial Landmarks Detection Model: 165.0ms
2020-07-06 01:37:42,841 [INFO] Gaze Estimation Model: 799.6ms
2020-07-06 01:37:42,844 [INFO] ========== End ==========
2020-07-06 01:37:57,753 [INFO] ========== Models Inference time ==========
2020-07-06 01:37:57,755 [INFO] Face Detection Model:52.3ms
2020-07-06 01:37:57,758 [INFO] Facial Landmarks Detection Model:1.1ms
2020-07-06 01:37:57,760 [INFO] Headpose Estimation Model:2.7ms
2020-07-06 01:37:57,760 [INFO] Gaze Estimation Model:3.1ms
2020-07-06 01:37:57,761 [INFO] ========== End ==========

GPU:-
FP32:
2020-07-06 01:47:58,942 [INFO] ========== Models Load time ==========
2020-07-06 01:47:58,956 [ERROR] Error running inference:Failed to create plugin /opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
Cannot load library '/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so': libOpenCL.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "src/main.py", line 81, in infer_on_stream
    face_detection_instant.load_model()
  File "/home/workspace/computer-pointer-controller/src/face_detection.py", line 46, in load_model
    supported_layers = self.core.query_network(self.model, self.device)
  File "ie_api.pyx", line 188, in openvino.inference_engine.ie_api.IECore.query_network
RuntimeError: Failed to create plugin /opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
Cannot load library '/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so': libOpenCL.so.1: cannot open shared object file: No such file or directory

2020-07-06 01:51:10,308 [INFO] ========== Models Load time ==========
2020-07-06 01:51:10,557 [INFO] Face Detection Model: 246.8ms
2020-07-06 01:51:10,647 [INFO] Headpose Estimation Model: 86.8ms
2020-07-06 01:51:10,719 [INFO] Facial Landmarks Detection Model: 70.9ms
2020-07-06 01:51:10,831 [INFO] Gaze Estimation Model: 110.7ms
2020-07-06 01:51:10,832 [INFO] ========== End ==========
2020-07-06 01:51:25,626 [INFO] ========== Models Inference time ==========
2020-07-06 01:51:25,628 [INFO] Face Detection Model:52.3ms
2020-07-06 01:51:25,630 [INFO] Facial Landmarks Detection Model:0.9ms
2020-07-06 01:51:25,632 [INFO] Headpose Estimation Model:2.9ms
2020-07-06 01:51:25,633 [INFO] Gaze Estimation Model:3.5ms
2020-07-06 01:51:25,634 [INFO] ========== End ==========
2020-07-06 01:54:25,373 [INFO] ========== Models Load time ==========
2020-07-06 01:54:25,378 [ERROR] Error running inference:Failed to create plugin /opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
Cannot load library '/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so': libOpenCL.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "src/main.py", line 81, in infer_on_stream
    face_detection_instant.load_model()
  File "/home/workspace/computer-pointer-controller/src/face_detection.py", line 46, in load_model
    supported_layers = self.core.query_network(self.model, self.device)
  File "ie_api.pyx", line 188, in openvino.inference_engine.ie_api.IECore.query_network
RuntimeError: Failed to create plugin /opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
Cannot load library '/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so': libOpenCL.so.1: cannot open shared object file: No such file or directory

2020-07-06 01:54:43,436 [INFO] ========== Models Load time ==========
2020-07-06 01:54:43,441 [ERROR] Error running inference:Device with "IGPU" name is not registered in the InferenceEngine
Traceback (most recent call last):
  File "src/main.py", line 81, in infer_on_stream
    face_detection_instant.load_model()
  File "/home/workspace/computer-pointer-controller/src/face_detection.py", line 46, in load_model
    supported_layers = self.core.query_network(self.model, self.device)
  File "ie_api.pyx", line 188, in openvino.inference_engine.ie_api.IECore.query_network
RuntimeError: Device with "IGPU" name is not registered in the InferenceEngine
2020-07-06 01:58:35,650 [INFO] ========== Models Load time ==========
2020-07-06 01:58:35,655 [ERROR] Error running inference:Failed to create plugin libdliaPlugin.so for device FPGA
Please, check your environment
Cannot load library 'libdliaPlugin.so': libdliaPlugin.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "src/main.py", line 81, in infer_on_stream
    face_detection_instant.load_model()
  File "/home/workspace/computer-pointer-controller/src/face_detection.py", line 46, in load_model
    supported_layers = self.core.query_network(self.model, self.device)
  File "ie_api.pyx", line 188, in openvino.inference_engine.ie_api.IECore.query_network
RuntimeError: Failed to create plugin libdliaPlugin.so for device FPGA
Please, check your environment
Cannot load library 'libdliaPlugin.so': libdliaPlugin.so: cannot open shared object file: No such file or directory

2020-07-06 01:59:32,261 [INFO] ========== Models Load time ==========
2020-07-06 01:59:32,275 [ERROR] Error running inference:Failed to create plugin libdliaPlugin.so for device FPGA
Please, check your environment
Cannot load library 'libdliaPlugin.so': libdliaPlugin.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "src/main.py", line 81, in infer_on_stream
    face_detection_instant.load_model()
  File "/home/workspace/computer-pointer-controller/src/face_detection.py", line 46, in load_model
    supported_layers = self.core.query_network(self.model, self.device)
  File "ie_api.pyx", line 188, in openvino.inference_engine.ie_api.IECore.query_network
RuntimeError: Failed to create plugin libdliaPlugin.so for device FPGA
Please, check your environment
Cannot load library 'libdliaPlugin.so': libdliaPlugin.so: cannot open shared object file: No such file or directory

2020-07-06 02:37:17,628 [INFO] ========== Models Load time ==========
2020-07-06 02:37:17,633 [ERROR] Error running inference:Device with "IGPU" name is not registered in the InferenceEngine
Traceback (most recent call last):
  File "src/main.py", line 81, in infer_on_stream
    face_detection_instant.load_model()
  File "/home/workspace/computer-pointer-controller/src/face_detection.py", line 46, in load_model
    supported_layers = self.core.query_network(self.model, self.device)
  File "ie_api.pyx", line 188, in openvino.inference_engine.ie_api.IECore.query_network
RuntimeError: Device with "IGPU" name is not registered in the InferenceEngine
2020-07-06 02:42:31,681 [INFO] ========== Models Load time ==========
2020-07-06 02:42:31,686 [ERROR] Error running inference:Failed to create plugin /opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
Cannot load library '/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so': libOpenCL.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "src/main.py", line 81, in infer_on_stream
    face_detection_instant.load_model()
  File "/home/workspace/computer-pointer-controller/src/face_detection.py", line 46, in load_model
    supported_layers = self.core.query_network(self.model, self.device)
  File "ie_api.pyx", line 188, in openvino.inference_engine.ie_api.IECore.query_network
RuntimeError: Failed to create plugin /opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
Cannot load library '/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so': libOpenCL.so.1: cannot open shared object file: No such file or directory

2020-07-06 03:07:33,480 [INFO] ========== Models Load time ==========
2020-07-06 03:07:33,740 [INFO] Face Detection Model: 257.3ms
2020-07-06 03:07:33,851 [INFO] Headpose Estimation Model: 108.7ms
2020-07-06 03:07:33,929 [INFO] Facial Landmarks Detection Model: 76.1ms
2020-07-06 03:07:34,065 [INFO] Gaze Estimation Model: 134.1ms
2020-07-06 03:07:34,066 [INFO] ========== End ==========
2020-07-06 03:07:48,974 [INFO] ========== Models Inference time ==========
2020-07-06 03:07:48,977 [INFO] Face Detection Model:52.4ms
2020-07-06 03:07:48,979 [INFO] Facial Landmarks Detection Model:0.8ms
2020-07-06 03:07:48,981 [INFO] Headpose Estimation Model:2.9ms
2020-07-06 03:07:48,982 [INFO] Gaze Estimation Model:3.5ms
2020-07-06 03:07:48,982 [INFO] ========== End ==========
2020-07-06 03:08:01,713 [INFO] ========== Models Load time ==========
2020-07-06 03:08:01,718 [ERROR] Error running inference:Failed to create plugin /opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
Cannot load library '/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so': libOpenCL.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "src/main.py", line 81, in infer_on_stream
    face_detection_instant.load_model()
  File "/home/workspace/computer-pointer-controller/src/face_detection.py", line 50, in load_model
    supported_layers = self.core.query_network(self.model, self.device)
  File "ie_api.pyx", line 188, in openvino.inference_engine.ie_api.IECore.query_network
RuntimeError: Failed to create plugin /opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
Cannot load library '/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so': libOpenCL.so.1: cannot open shared object file: No such file or directory

2020-07-06 03:23:28,800 [INFO] ========== Models Load time ==========
2020-07-06 03:23:29,039 [INFO] Face Detection Model: 235.9ms
2020-07-06 03:23:29,148 [INFO] Headpose Estimation Model: 107.1ms
2020-07-06 03:23:29,222 [INFO] Facial Landmarks Detection Model: 71.0ms
2020-07-06 03:23:29,351 [INFO] Gaze Estimation Model: 128.4ms
2020-07-06 03:23:29,353 [INFO] ========== End ==========
2020-07-06 03:23:44,212 [INFO] ========== Models Inference time ==========
2020-07-06 03:23:44,215 [INFO] Face Detection Model:51.6ms
2020-07-06 03:23:44,217 [INFO] Facial Landmarks Detection Model:0.8ms
2020-07-06 03:23:44,219 [INFO] Headpose Estimation Model:2.8ms
2020-07-06 03:23:44,219 [INFO] Gaze Estimation Model:3.4ms
2020-07-06 03:23:44,220 [INFO] ========== End ==========
2020-07-06 03:24:04,731 [INFO] ========== Models Load time ==========
2020-07-06 03:24:04,986 [INFO] Face Detection Model: 252.4ms
2020-07-06 03:24:05,109 [INFO] Headpose Estimation Model: 120.4ms
2020-07-06 03:24:05,184 [INFO] Facial Landmarks Detection Model: 72.6ms
2020-07-06 03:24:05,315 [INFO] Gaze Estimation Model: 129.6ms
2020-07-06 03:24:05,316 [INFO] ========== End ==========
2020-07-06 03:24:20,353 [INFO] ========== Models Inference time ==========
2020-07-06 03:24:20,356 [INFO] Face Detection Model:52.2ms
2020-07-06 03:24:20,358 [INFO] Facial Landmarks Detection Model:0.9ms
2020-07-06 03:24:20,360 [INFO] Headpose Estimation Model:2.9ms
2020-07-06 03:24:20,361 [INFO] Gaze Estimation Model:3.5ms
2020-07-06 03:24:20,361 [INFO] ========== End ==========
2020-07-06 03:26:02,103 [INFO] ========== Models Load time ==========
2020-07-06 03:26:02,108 [ERROR] Error running inference:Failed to create plugin /opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
Cannot load library '/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so': libOpenCL.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "src/main.py", line 81, in infer_on_stream
    face_detection_instant.load_model()
  File "/home/workspace/computer-pointer-controller/src/face_detection.py", line 46, in load_model
    supported_layers = self.core.query_network(self.model, self.device)
  File "ie_api.pyx", line 188, in openvino.inference_engine.ie_api.IECore.query_network
RuntimeError: Failed to create plugin /opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
Cannot load library '/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so': libOpenCL.so.1: cannot open shared object file: No such file or directory

2020-07-06 05:14:56,246 [INFO] ========== Models Load time ==========
2020-07-06 05:14:56,495 [INFO] Face Detection Model: 245.9ms
2020-07-06 05:14:56,614 [INFO] Headpose Estimation Model: 117.4ms
2020-07-06 05:14:56,691 [INFO] Facial Landmarks Detection Model: 74.1ms
2020-07-06 05:14:56,827 [INFO] Gaze Estimation Model: 135.2ms
2020-07-06 05:14:56,829 [INFO] ========== End ==========
2020-07-06 05:15:11,828 [INFO] ========== Models Inference time ==========
2020-07-06 05:15:11,831 [INFO] Face Detection Model:52.5ms
2020-07-06 05:15:11,833 [INFO] Facial Landmarks Detection Model:0.9ms
2020-07-06 05:15:11,835 [INFO] Headpose Estimation Model:2.9ms
2020-07-06 05:15:11,836 [INFO] Gaze Estimation Model:3.5ms
2020-07-06 05:15:11,836 [INFO] ========== End ==========
